### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by simme** [mattgallagher/Clocks#1]
Hello,

Really like the concepts in this sample app (and the accompanying talk was great).

Just a question though, how do you see this scaling to a larger, more complex, app? Seems like putting all state mutating methods on a single object might grow out of control. Curious if you have given this any thought?

I understand why it's not possible to have mutating methods on each "sub-state". And without giving it too much thought I fail to come up with anything obvious to mitigate the "massive state syndrom".

Best,
Simon

**Comment by mattgallagher** [comment]
In the Clocks app, the ViewState is a single interface (a "class" type at the top for "identity" and everything below that is a "struct" value-type). The "scaling" you're asking about is equivalent to asking how you put a single interface around any complex structure and it can be solved through standard software engineering approaches.

SQL solves this problem for databases – use a structured language at the interface level. Key-value storage can handle simpler scenarios – give up on complete "methods" and just get/set values and you can easily handle a large number of "keys".

Alternately, you can nest interfaces inside interfaces and use different kinds of observing and notifying to keep the tree consistent. Key-Value Observing or Reactive Programming can handle these situations.
